# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'epic7_automator_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(501, 657)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(380, 10, 111, 23))
        self.start_button.setObjectName("start_button")
        self.get_app_button = QtWidgets.QPushButton(self.centralwidget)
        self.get_app_button.setGeometry(QtCore.QRect(10, 10, 101, 23))
        self.get_app_button.setObjectName("get_app_button")
        self.app_combo_box = QtWidgets.QComboBox(self.centralwidget)
        self.app_combo_box.setGeometry(QtCore.QRect(10, 50, 261, 22))
        self.app_combo_box.setObjectName("app_combo_box")
        self.app_combo_box.addItem("")
        self.launch_app_button = QtWidgets.QPushButton(self.centralwidget)
        self.launch_app_button.setGeometry(QtCore.QRect(120, 10, 75, 23))
        self.launch_app_button.setObjectName("launch_app_button")
        self.shutdown_button = QtWidgets.QPushButton(self.centralwidget)
        self.shutdown_button.setGeometry(QtCore.QRect(380, 50, 111, 23))
        self.shutdown_button.setObjectName("shutdown_button")
        self.screenshot_button = QtWidgets.QPushButton(self.centralwidget)
        self.screenshot_button.setGeometry(QtCore.QRect(10, 80, 75, 23))
        self.screenshot_button.setObjectName("screenshot_button")
        self.screenshot_view = QtWidgets.QGraphicsView(self.centralwidget)
        self.screenshot_view.setGeometry(QtCore.QRect(10, 110, 480, 270))
        self.screenshot_view.setObjectName("screenshot_view")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 390, 54, 12))
        self.label.setObjectName("label")
        self.log_text_browser = QtWidgets.QTextBrowser(self.centralwidget)
        self.log_text_browser.setGeometry(QtCore.QRect(10, 410, 481, 192))
        self.log_text_browser.setObjectName("log_text_browser")
        self.status_label = QtWidgets.QLabel(self.centralwidget)
        self.status_label.setGeometry(QtCore.QRect(210, 80, 111, 16))
        self.status_label.setObjectName("status_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 501, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.app_combo_box.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.start_button.setText(_translate("MainWindow", "Start emulator"))
        self.get_app_button.setText(_translate("MainWindow", "get app list"))
        self.app_combo_box.setCurrentText(_translate("MainWindow", "Click the button above to get App list."))
        self.app_combo_box.setItemText(0, _translate("MainWindow", "Click the button above to get App list."))
        self.launch_app_button.setText(_translate("MainWindow", "launch app"))
        self.shutdown_button.setText(_translate("MainWindow", "Shutdown emulator"))
        self.screenshot_button.setText(_translate("MainWindow", "Screenshot"))
        self.label.setText(_translate("MainWindow", "Log info"))
        self.status_label.setText(_translate("MainWindow", "TextLabel"))
