logger:
  logger_name: "Epic7_Automation"
  log_dir: "C:/Users/loren/Projects/Epic7_Automation_Python/log"
  log_name: "E7A_TIMESTAMP"

emulator:
  vm_index: 0
  vm_name: ~

#name: abc
#li:
#  -list1
#  -list2
